### ISSUE TITLE
NoMethodError: undefined method `fetch_value' for nil:NilClass

### ISSUE THREAD

**Issue by tbrammar** [mceachen/closure_tree#157]
I'm getting the following error when trying to create a tag:

`````
2.1.5 :003 > Tag.create(name: 'Grandpa')
   (0.4ms)  BEGIN
  Tag Exists (1.8ms)  SELECT  1 AS one FROM "tags" WHERE "tags"."token" = $1 LIMIT 1  [["token", "2577"]]
  SQL (1.0ms)  INSERT INTO "tags" ("name", "token", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "Grandpa"], ["token", "2577"], ["created_at", "2015-06-01 14:08:24.111811"], ["updated_at", "2015-06-01 14:08:24.111811"]]
   (0.7ms)  SELECT pg_try_advisory_lock(1814493058,0) AS t85f1ad91498c46cf2f126412bc33ec1a
  SQL (1.6ms)  INSERT INTO "tag_hierarchies" ("ancestor_id", "descendant_id", "generations") VALUES ($1, $2, $3)  [["ancestor_id", 1], ["descendant_id", 1], ["generations", 0]]
   (1.5ms)  UPDATE "tags"
SET "click_count" = t.seq + -1
FROM (
  SELECT "id" AS id, row_number() OVER(ORDER BY click_count) AS seq
  FROM "tags"
  WHERE "parent_id" IS NULL 
) AS t
WHERE "tags"."id" = t.id

  Tag Load (0.4ms)  SELECT  "tags".* FROM "tags" WHERE "tags"."token" = $1 LIMIT 1  [["token", "1"]]
   (0.5ms)  SELECT pg_advisory_unlock(1814493058,0) AS t384cb09eac170a8d7fe72390dfc09525
   (0.5ms)  ROLLBACK
#<NoMethodError: undefined method `[]' for nil:NilClass>
NoMethodError: undefined method `fetch_value' for nil:NilClass
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/attribute_methods/read.rb:93:in `_read_attribute'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/attribute_methods/read.rb:87:in `read_attribute'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/attribute_methods.rb:359:in `[]'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:103:in `last_chain_scope'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:139:in `add_constraints'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:39:in `scope'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/association_scope.rb:5:in `scope'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/association.rb:97:in `association_scope'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/association.rb:86:in `scope'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:423:in `scope'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/collection_proxy.rb:37:in `initialize'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:106:in `new'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:106:in `create'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:41:in `reader'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/activerecord-4.2.1/lib/active_record/associations/builder/association.rb:115:in `children'
  from /Users/username/.rvm/gems/ruby-2.1.5@gsp/gems/closure_tree-5.2.0/lib/closure_tree/hierarchy_maintenance.rb:82:in `block in rebuild!'
... 28 levels...
`````

Here's my `Tag` model:
````````
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings, source: :taggable, source_type: 'Post'

  attr_accessible :name

  has_closure_tree order: 'click_count'

  before_validation :generate_token

  validates :name, :token, presence: true

  def generate_token
    self.token = loop do
      random_token = SecureRandom.hex(2)
      break random_token unless Tag.where(token: random_token).exists?
    end
  end

  def to_param
    token
  end

  def self.find(input)
    find_by_token(input)
  end
end
``````

closure_tree 5.2.0
rails 4.2.1
activerecord 4.2.1
ruby 2.1.5

**Comment by mceachen** [comment]
Wow. That's a pretty unique id generator, and overriding find() like that
is new to me. I've had pretty much nothing but pain and suffering when I
override base active record methods like that.

Try unhooking that method and see if that's the issue. Also, there are many
tests that run with a model that has an uuid ID generator, take a look at
that code to see a working model example.

**Comment by tbrammar** [comment]
Yep, it was the `self.find` method. I never wrote this part of the code base so it didn't occur to me that those methods could affect it. Closing this now.

**Comment by mceachen** [comment]
Look how diplomatic I was being, calling it "unique" instead of "the worst
idea evar"

**Comment by tbrammar** [comment]
hahaha (shh, the originator might be on here somewhere)
