### ISSUE TITLE
I got error Errno::EACCES (Permission denied @ utime_failed - .lock-ClosureTreeQuestion-457297341):

### ISSUE THREAD

**Issue by rajcybage** [mceachen/closure_tree#213]
Here details

````
Errno::EACCES: Permission denied @ utime_failed - .lock-ClosureTreeQuestion-457297341
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/fileutils.rb:1163:in `utime'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/fileutils.rb:1163:in `block in touch'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/fileutils.rb:1160:in `each'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/fileutils.rb:1160:in `touch'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/flock.rb:17:in `file_io'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/flock.rb:23:in `try_lock'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/base.rb:74:in `yield_with_lock'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/base.rb:65:in `yield_with_lock_and_timeout'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/base.rb:48:in `with_advisory_lock_if_needed'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/concern.rb:16:in `with_advisory_lock_result'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/concern.rb:10:in `with_advisory_lock'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/closure_tree-6.0.0/lib/closure_tree/support.rb:103:in `with_advisory_lock'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/closure_tree-6.0.0/lib/closure_tree/hierarchy_maintenance.rb:63:in `rebuild!'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/closure_tree-6.0.0/lib/closure_tree/hierarchy_maintenance.rb:39:in `_ct_after_save'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:228:in `call'
... 14 levels...
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:286:in `block in save'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:285:in `save'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/persistence.rb:34:in `create'
        from (irb):2
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'irb(main):003:0> exit
``````

I am using windows 7
 closure_tree (6.0.0)
  rails 4.2

**Comment by mceachen** [comment]
Your current user doesn't have permission to write to that directory.

Either specify a different directory to save your lock file in, or use a different db engine (like MySQL or Postgres)

**Comment by rajcybage** [comment]
But I did not upload or create file to any directory just upload.
