### ISSUE TITLE
'rails g closure_tree:migration XXX' failed inside rails engine

### ISSUE THREAD

**Issue by brxue** [mceachen/closure_tree#233]
'rails g closure_tree:migration XXX' will report following error when using closure_tree inside a rails engine, any comment? 

``` ruby
/usr/share/gems/gems/abrt-0.0.6/lib/abrt.rb:6:in `require': cannot load such file -- abrt/handler (LoadError)
        from /usr/share/gems/gems/abrt-0.0.6/lib/abrt.rb:6:in `block in <top (required)>'
/home/brxue/.gem/ruby/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `const_get': uninitialized constant Message (NameError)
        from /home/brxue/.gem/ruby/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
        from /home/brxue/.gem/ruby/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
        from /home/brxue/.gem/ruby/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
        from /home/brxue/.gem/ruby/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
        from /home/brxue/.gem/ruby/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
        from /home/brxue/.gem/ruby/gems/closure_tree-5.2.0/lib/generators/closure_tree/migration_generator.rb:33:in `target_class'
        from /home/brxue/.gem/ruby/gems/closure_tree-5.2.0/lib/generators/closure_tree/migration_generator.rb:37:in `ct'
        from /home/brxue/.gem/ruby/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/brxue/.gem/ruby/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/brxue/.gem/ruby/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /home/brxue/.gem/ruby/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /home/brxue/.gem/ruby/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /home/brxue/.gem/ruby/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /home/brxue/.gem/ruby/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /home/brxue/.gem/ruby/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/brxue/.gem/ruby/gems/railties-4.2.7.1/lib/rails/generators.rb:157:in `invoke'
        from /home/brxue/.gem/ruby/gems/railties-4.2.7.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
        from /home/brxue/.gem/ruby/gems/railties-4.2.7.1/lib/rails/engine/commands.rb:19:in `require'
        from /home/brxue/.gem/ruby/gems/railties-4.2.7.1/lib/rails/engine/commands.rb:19:in `<top (required)>'
        from bin/rails:12:in `require'
        from bin/rails:12:in `<main>'
```

Thanks,
Brian

**Comment by mceachen** [comment]
What is the abrt gem? That's where your stack points.

**Comment by brxue** [comment]
The abrt gem should be internally used by Rails. The real error should be this line,

uninitialized constant Message (NameError)

where Message is my intended model in app/models/message.rb.

**Comment by brxue** [comment]
Hi @mceachen ,

I took a look further the migration generator code in `lib/generators/closure_tree/migration_generator.rb`. The problem should be that it tries to call `class_name.constantize` to get a `Class` which is `Message` in my case, but in Rails Engine top directory the application context is not set up unless the command is executed from application's directory (typically test/dummy). 

```bash
[brxue@localhost ~/rails_plugin_full]$ rails --help
Usage: rails COMMAND [ARGS]

The common Rails commands available for engines are:
 generate    Generate new code (short-cut alias: "g")
 destroy     Undo code generated with "generate" (short-cut alias: "d")

All commands can be run with -h for more information.

If you want to run any commands that need to be run in context
of the application, like `rails server` or `rails console`,
you should do it from application's directory (typically test/dummy).
```

What's the considerations here to require a `Message` class instead of just a string of "message"? From my view it should be enough to generate the migration.

Thanks,
Brian

**Comment by brxue** [comment]
For anyone who may interest, a workaround for this issue is to run `rails g closure_tree:migration XXX` under `test/dummy` application inside Rails Engine, and then move the generated migration to `db/migrate`.

**Comment by mceachen** [comment]
Without more information to repro, I'll close as work-aroundable.
